name: merge main workflow

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Build and test
              uses: ./.github/workflows/build_and_test.yml
