name: push to main workflow

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
            uses: actions/checkout@v2
            - name: Build and Test
            uses: ./.github/workflows/build_and_test.yml
            - name: Docker and Deploy
            uses: ./.github/workflows/docker_and_deploy.yml

        