name: push to main workflow

on:
    pull_request:
        branches:
            - main

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        uses: ./.github/workflows/build_and_test.yml
    docker_and_deploy:
        runs-on: ubuntu-latest
        uses: ./.github/workflows/docker_and_deploy.yml

        